winget install -e --id GIMP.GIMP.3 --accept-source-agreements --accept-package-agreements
winget install -e --id Git.Git --accept-source-agreements --accept-package-agreements
winget install -e --id Microsoft.VisualStudioCode --accept-source-agreements --accept-package-agreements
winget install -e --id Microsoft.SQLServerManagementStudio.21 --accept-source-agreements --accept-package-agreements
winget install -e --id SlackTechnologies.Slack --accept-source-agreements --accept-package-agreements
winget install -e --id dotPDN.PaintDotNet --accept-source-agreements --accept-package-agreements
winget install -e --id Postman.Postman --accept-source-agreements --accept-package-agreements
winget install -e --id VideoLAN.VLC --accept-source-agreements --accept-package-agreements
winget install -e --id Inkscape.Inkscape --accept-source-agreements --accept-package-agreements
winget install -e --id Spotify.Spotify --accept-source-agreements --accept-package-agreements
winget install -e --id Greenshot.Greenshot --accept-source-agreements --accept-package-agreements
winget install -e --id Microsoft.PowerToys --accept-source-agreements --accept-package-agreements
winget install -e --id Microsoft.Teams --accept-source-agreements --accept-package-agreements
winget install -e --id 1Password.1Password --accept-source-agreements --accept-package-agreements
winget install -e --id alexx2000.DoubleCommander --accept-source-agreements --accept-package-agreements
winget install -e --id OpenWhisperSystems.Signal --accept-source-agreements --accept-package-agreements
winget install -e --id Docker.DockerDesktop --accept-source-agreements --accept-package-agreements
winget install -e --id Oracle.MySQLWorkbench --accept-source-agreements --accept-package-agreements
winget install -e --id BlenderFoundation.Blender --accept-source-agreements --accept-package-agreements
winget install -e --id Google.Chrome --accept-source-agreements --accept-package-agreements
winget install -e --id Flashforge.FlashPrint --accept-source-agreements --accept-package-agreements
winget install -e --id TortoiseSVN.TortoiseSVN --accept-source-agreements --accept-package-agreements
winget install -e --id Canonical.Ubuntu.2404 --accept-source-agreements --accept-package-agreements
